[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
monitor_filters = esp32_exception_decoder

lib_deps =
  bblanchon/ArduinoJson@^6.21.4
  knolleary/PubSubClient@^2.8
